[package]
name = "modules"
version = "0.1.0"
edition = "2021"

[dependencies]
eurorack = { path = "../eurorack/" }
midir = "0.7.0"
midly = "0.5.2"
module = { path = "../module/" }
portable-atomic = { version = "0.2.1", features = ["float"] }
thiserror = "1.0"
widgets = { path = "../widgets/" }
