[package]
name = "sequencer"
version = "0.1.0"
edition = "2021"

[dependencies]
eurorack = { path = "../eurorack/" }
module = { path = "../module/" }
rack = { path = "../rack/" }
widgets = { path = "../widgets/" }
