[package]
name = "oxcable_modular_main"
version = "0.1.0"
edition = "2021"

[dependencies]
audio_host = { path = "../audio_host/" }
anyhow = "1.0"
eframe = "0.17.0"
gui = { path = "../gui/" }
module = { path = "../module/" }
modules = { path = "../modules/" }
rack = { path = "../rack/" }
