[package]
name = "oxcable_modular_main"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
cpal = "0.13.4"
oscillators = { path = "../oscillators/" }
rack = { path = "../rack/" }
sequencer = { path = "../sequencer/" }
utility_modules = { path = "../utility_modules/" }
