[package]
name = "audio_host"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.13.5"
ctrlc = "3.4.2"
eurorack = { path = "../eurorack/" }
module = { path = "../module/" }
rack = { path = "../rack/" }
thiserror = "1.0.56"
