[package]
name = "utility_modules"
version = "0.1.0"
edition = "2021"

[dependencies]
atomic_float = "0.1.0"
eurorack = { path = "../eurorack/" }
midir = "0.7.0"
midly = "0.5.2"
module = { path = "../module/" }
thiserror = "1.0"
widgets = { path = "../widgets/" }
