[package]
name = "oscillators"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.17.0"
eurorack = { path = "../eurorack/" }
gui = { path = "../gui/" }
module = { path = "../module/" }
rack = { path = "../rack/" }
