[package]
name = "filters"
version = "0.1.0"
edition = "2021"

[dependencies]
atomic_float = "0.1.0"
eurorack = { path = "../eurorack/" }
module = { path = "../module/" }
rack = { path = "../rack/" }
widgets = { path = "../widgets/" }
